config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'error' => 'pages#error'

  resources :lists do
    resources :items, except: :index do
      member do
        post 'toggle'
      end
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items, dependent: :destroy
	belongs_to :user
	
	validates :title, presence: true, length: {maximum: 30}
	validates :description, length: {maximum: 150}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_item, only: [:edit, :update, :destroy]
	before_action :find_list, only: [:edit, :update, :destroy]
	before_filter :require_permission, only: [:new, :edit]

	def new
		@list = List.find(params[:list_id])
		@item = Item.new
	end

	def create
		@list = List.find(params[:list_id])
		@item = @list.items.build(item_params)
		if @item.save
			redirect_to @list
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @item.update(item_params)
			redirect_to @list
		else
			render :edit
		end
	end

	def destroy
		@item.destroy
		redirect_to @list
	end

	def toggle
		@item = Item.find(params[:id])
		@item.update_attributes(:is_complete => params[:is_complete])
		redirect_to root_path
	end

	private

		def item_params
			params.require(:item).permit(:task)
		end

		def find_item
			@item = Item.find(params[:id])
		end

		def find_list
			@list = List.find(params[:list_id])
		end

		def require_permission
			if current_user != find_list.user
				flash[:error] = "Error"
				redirect_to error_path
			end
		end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_list, only: [:show, :edit, :update, :destroy, :toggle]
	before_filter :require_permission, only: :edit

	def index
		@lists = current_user.lists
	end

	def new
		@list = current_user.lists.build
	end

	def create
		@list = current_user.lists.build(list_params)
		if @list.save
			redirect_to @list
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @list.update(list_params)
			redirect_to @list
		else
			render 'edit'
		end
	end

	def destroy
		@list.destroy
		redirect_to lists_path
	end


	private

		def list_params
			params.require(:list).permit(:title, :description)
		end

		def find_list
			@list = List.find(params[:id])
		end

		def require_permission
			if current_user != List.find(params[:id]).user
				flash[:success] = "Here"
				redirect_to error_path
			end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		if user_signed_in?
			redirect_to lists_path
		end
	end

	def error
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>
	<div class="form-group">
		<%= f.label :task %>
		<%= f.text_field :task, class: "form-control", placeholder: "Task" %>
	</div>


	<%= f.submit(@item.new_record? ? "Create Item" : "Edit Item", class: "btn btn-success") %>
<% end %>

app/views/items/edit.html.erb
<%= render 'shared/errors', obj: @item %>
<%= render 'form' %>

app/views/items/index.html.erb
<h1><%= @list.title %></h1>
<% @items.each do |item| %>
	- <%= item.task %>
<% end %>

app/views/items/new.html.erb
<%= render 'shared/errors', obj: @item %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Todo Application</a>
		    </div>
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		      	<% if user_signed_in? %>
							<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		      	<% else %>
							<li><%= link_to "Login", new_user_session_path%></li>
		      	<% end %>
		      </ul>
		    </div>
		  </div>
		</nav>
	</header>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


	<%= yield %>

	<footer>
		Josip Dorvak &copy; 2016
	</footer>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control", placeholder: "Title" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control", placeholder: "Description" %>
	</div>


	<%= f.submit(@list.new_record? ? "Create List" : "Edit List", class: "btn btn-success") %>
<% end %>

app/views/lists/edit.html.erb
<%= render 'shared/errors', obj: @list %>
<%= render 'form' %>

app/views/lists/index.html.erb
<div class="list-group">
	<% @lists.each do |list| %>
		<%= link_to list, class: "list-group-item" do %>
			<%= list.title %><span class="badge">#</span>
		<% end %>
	<% end %>
</div>

app/views/lists/new.html.erb
<%= render 'shared/errors', obj: @list %>
<%= render 'form' %>

app/views/lists/show.html.erb
<h3><%= @list.title %></h3>
<% if @list.description? %>
	<div class="jumbotron">
		<%= @list.description %>
	</div>
<% end %>

<% @list.items.each do |item| %>
	<div class="task">
		<%= check_box_tag 'complete', item.id, item.is_complete, class: "task-check" %>
		<span><%= item.task %></span>
		<%= link_to "Delete Task", list_item_path(@list, item), method: :delete, data: {confirm: "Are you sure?"} %>
		<%= item.is_complete %>
	</div>
<% end %>

<script>
	$(".task-check").bind('change', function(){
    $.ajax({
      url: '/lists/'+ <%= @list.id %> +'/items/' +this.value+ '/toggle',
      type: 'POST',
      data: {"is_complete": this.checked}
    });
    if($(this).is(":checked")){
    	$(this).addClass("complete");
    }else{
    	$(this).removeClass("complete");
    }
});

 $(".task-check").trigger('change');
</script>

app/views/pages/error.html.erb
<h1>STOP!</h1>
<h4>You are not allowed to do that, or have reached this page in error</h4>
<h6>You may go <%= link_to "BACK", :back %> to what you were doing, or visit the <%= link_to "Homepage", root_path %>.
<div id="error-image">
	<%= image_tag "stop.jpg", size: "500" %>
</div>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
	<h2>Get Started With [Insert App Title]</h2>
	<h4>Example text 1234567</h4>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-primary" %>

	<p>Have an account? <%= link_to "Log in here", new_user_session_path %></p>
</div>

<div class="home-description text-center">
	<h3>More example text here</h3>
	<div class="row">
		<div class="col-md-4">
			Area 1
		</div>
		<div class="col-md-4">
			Area 2
		</div>
		<div class="col-md-4">
			Area 3
		</div>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<ul>
		<% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>